<?php
/** @var Cminds\Multiwishlist\Block\Wishlist\Catalog\ProductList\Item\AddTo\Wishlist $block */
?>
<?php $wishlists = $block->getWishlists(); ?>
<?php if ($block->getWishlistHelper()->isAllow()): ?>
    <a href="#"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       data-action="add-to-wishlist"
       role="button">
       <i class="fas fa-heart"></i>
    </a>
<?php endif; ?>