<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>

<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>

<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
    $_postDate = $_post->getData("publish_time");
    $_helper = $this->helper('Redgiant\Berserk\Helper\Data');
?>

<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?> brs-posts-container brs-posts-container_right-divider brs-post-container_bottom-divider pt-20" >
        
        <div class="brk-post-full">
			<div class="brk-post-full__meta font__family-montserrat font__weight-semibold font__size-13 line__height-14 text-uppercase"><a href="#" class="brk-post-full__meta-date"><i class="far fa-clock"></i> <span><?php echo date("M d, y", strtotime($_postDate)); ?></span> </a><a href="#" class="brk-post-full__meta-comments"><i class="far fa-comments"></i> <span><?php echo '' ?></span></a></div>
			<h2 class="brk-post-full__title font__family-montserrat font__size-36 font__weight-semibold line__heigt-38 mt-10 mb-35"><?php echo $_postName; ?></h2>
       
            <div class="post-content">
                <div class="post-description clearfix">
                    <div class="post-text-hld">
                        <?php echo $_helper->filterContent($block->getContent()) ?>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="post-header">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <h2 class="post-title theme-color">
                
            </h2>
          <!--  <?php echo $this->getInfoHtml() ?> -->
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>