<?php
/**
 */
 $berserk_helper = $this->helper('Redgiant\Berserk\Helper\Data');
?>
<?php if ($block->canShowBlock()): ?>
    <?php
    $filters     = $block->getFilters();
    $layerConfig = $this->helper('Redgiant\LayeredNavigation\Helper\Data')->getLayerConfiguration($filters);
    $filtered    = count($block->getLayer()->getState()->getFilters());
    ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>

        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */
        echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */
                echo __('Filter') ?></strong>
        </div>
        <div class="block-content filter-content" data-mage-init='{"rgLayer": <?php echo $layerConfig ?>}'>
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getClearUrl() ?>"
                       class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                            echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($filters

                           as $key => $filter): ?>
        <?php if ($filter->getItemsCount()): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2"
                    class="block-subtitle filter-subtitle"><?php echo __('Filter') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content">
                <?php $wrapOptions = true;
                endif; ?>
                <?php if($filter->getRequestVar() == 'cat') continue;
                $_class = $filter->getRequestVar() == 'cat' || $filter->getRequestVar() == 'size' || $filter->getRequestVar() == 'color' || $filter->getRequestVar() == 'price' ? 'active':'';?>
                <div data-role="ln_collapsible" class="filter-options-item <?php echo $_class;?>"
                     attribute="<?php echo $filter->getRequestVar() ?>">
                    <div data-role="ln_title" class="filter-options-title"><span><?php /* @escapeNotVerified */
                        echo __($filter->getName()) ?></span></div>
                    <div data-role="ln_content" class="filter-options-content"><?php /* @escapeNotVerified */
                        echo $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>

            <?php echo $block->getChildHtml('layer_additional_info') ?>
        </div>
    </div>
    <script>
        require([
            'jquery'
        ], function ($) {
            $(document).ready(function(){
                var mq = window.matchMedia( "(min-width: 992px)" )
                if (mq.matches && $('body').hasClass('page-layout-1column') ) {
                    $('.block.filter  .filter-options-item').each(function(){
                        $(this).removeClass('active');
                    });
                }
            });
        });
    </script>
<?php endif; ?>
