<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="brk-cur brk-header__item switcher switcher-currency currency">
    <span class="brk-switcher__selected"><?php echo $block->escapeHtml($currentCurrencyCode) ?></span>
    <ul class="brk-switcher__option">
        <?php foreach ($currencies as $_code => $_name): ?>
            <?php if ($_code != $currentCurrencyCode): ?>
                <li>
                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
    <i class="fa fa-caret-down" aria-hidden="true"></i>
</div>
<?php endif; ?>