<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="form password forget brk-form-strict"
      action="<?php echo $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php echo $block->escapeHtml(__('* Required Fields')) ?>">
        <div class="field note"><?php echo $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')); ?></div>
        <div class="field email required">
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" placeholder="<?php echo $block->escapeHtml(__('Email')) ?>" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary btn-backgrounds btn-backgrounds btn-backgrounds_280 btn-backgrounds_white font__family-montserrat font__weight-bold text-uppercase font__size-13 z-index-2 text-center letter-spacing-20 mt-10"><span><?php echo $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getLoginUrl()) ?>"><span><?php echo $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
