<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var \Magento\Customer\Block\Form\Login\Info $block
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <h1  id="block-new-customer-heading" class="font__family-montserrat font__weight-bold font__size-42 line__height-42 mt-0 mb-45" role="heading" aria-level="2"><?php echo $block->escapeHtml(__('Register')) ?></h1>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?php echo $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php echo $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary btn-backgrounds btn-backgrounds btn-backgrounds_280 btn-backgrounds_white font__family-montserrat font__weight-bold text-uppercase font__size-13 z-index-2 text-center letter-spacing-20 mt-10 brk-library-rendered">                
                    <span><?php echo $block->escapeHtml(__('Sign UP')) ?></span>
                    <span class="before"><i class="fas fa-user"></i></span>
                </a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery',
        'form-controls'
    ], function($) {
        
        $('.form-login').addClass('brk-form-strict');
        $('.form-login .control').each(function(e) {
            $(this).find('input').attr('placeholder', $(this).prev().text());
            $(this).prev().remove();
        });

        Berserk.behaviors.form_controls.attach($('body'), {timeout_delay: 2000});
        
        /*setTimeout(function() {
            $('.form-login').find('.brk-form-wrap').each(function(e) {
                if ($(this).find('.input-text').val() != "") {
                    $(this).addClass('brk-form-wrap-active');
                }
            });
        }, 1000);*/
    });
</script>