<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update Wish List') ?>" class="action update btn btn-inside-out btn-lg border-radius-25 btn-shadow">
        <span class="before"><?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
        <span class="text"><?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
        <span class="after"><?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
    </button>
<?php endif;?>
