<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary customize btn btn-inside-out btn-lg border-radius-25 btn-shadow pl-50 pr-50 brk-library-rendered"
                type="button">
            <span class="before"><?php /* @escapeNotVerified */ echo __('Customize and Add to Cart'); ?></span>
            <span class="text"><?php /* @escapeNotVerified */ echo __('Customize and Add to Cart'); ?></span>
            <span class="after"><?php /* @escapeNotVerified */ echo __('Customize and Add to Cart'); ?></span>
        </button>
    </div>
<?php endif;?>
