<?php
/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <a href="#"
       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
       class="use-ajax action action towishlist"
       data-action="add-to-wishlist">
        <span><?= $block->escapeHtml(__('Move to Wishlist')) ?></span>
    </a>
<?php endif ?>
