<?php
use Magento\Framework\App\Action\Action;
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper( 'Magento\Catalog\Helper\Output' );
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$_berserkhelper = $this->helper( 'Redgiant\Berserk\Helper\Data' );

$_colClass = '';
$_rowClass = '';
$_sale_label = $_berserkhelper->getConfig('berserk_settings/catalog/sale_label');
$_new_label = $_berserkhelper->getConfig('berserk_settings/catalog/new_label');
$_label_type = $_berserkhelper->getConfig('berserk_settings/catalog/label_type'); 
$_show_review = $this->getData("rating_star");
if(!$_show_review)
    $_show_review = $_berserkhelper->getConfig('berserk_settings/catalog/show_review');
$_review_model = $_berserkhelper->getModel('\Magento\Review\Model\Review');
$_show_percent = $_berserkhelper->getConfig('berserk_settings/catalog/show_percent');
$_flipbox = '';
$aspect_ratio = $this->getData("aspect_ratio");
if($aspect_ratio == null) {
    $aspect_ratio = 0;
}
$image_width = $this->getData("image_width");
if(!$image_width) {
    $image_width = 300;
}
$image_height = $this->getData("image_height");
if($aspect_ratio)
    $image_height = $image_width;
if(!$image_height) {
    $image_height = 300;  
}
$_categoryid = $this->getData("category_id");
if(!$_categoryid) {
    $_categoryid = $_berserkhelper->getRootCategoryId(); 
}
$perrow = $this->getData("per_row");    
if($perrow == null) {
    $perrow = 6;
}
$_colClass = $_berserkhelper->getColClass( $perrow );
?>
<?php if ( !$_productCollection->count() ): ?>
    <div class="message info empty">
        <div><?php echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="filterproducts isotope-grid">
        <div class="brk-shop-grid-filter">
            <ul class="brk-shop-grid-filter__button brk-shop-grid-filter__button_style-1">
				<li class="checked" data-filter="*">
					<div class="brk-shop-grid-filter__button-text"><i class="fal fa-th"></i>All</div><span class="before brk-base-bg-gradient-14"></span>
                </li>
                <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
                    $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($_categoryid);
                    $_filter_html = '';
                    $_categoryIds = array('');
                    foreach($_productCollection as $_product):
                        $_parents = $_product->getCategoryIds();
                        foreach($_parents as $_parent) {
                            if( $_parent != $_berserkhelper->getRootCategoryId() && !in_array( $_parent, $_categoryIds )){
                                array_push($_categoryIds, $_parent);
                            }
                        }
                    endforeach;
                    if(count($_categoryIds)):
                    foreach($_categoryIds as $_catid):
                        if($_catid != ''):
                            $_subcat = $objectManager->create('Magento\Catalog\Model\Category')->load($_catid);
                ?>
                <li data-filter="<?php echo '.' . $_subcat->getData('url_key'); ?>">
					<div class="brk-shop-grid-filter__button-text"><?php echo $_subcat->getName() ?></div><span class="before brk-base-bg-gradient-14"></span>
                </li>
                    <?php
                        endif;
                    endforeach; 
                    endif; ?>
            </ul>
            <div class="brk-shop-grid-filter__items row no-gutters">
                <?php foreach($_productCollection as $_product): 
                        $_categoryIds = $_product->getCategoryIds();
                        $_filters = '';
                        foreach($_categoryIds as $_catId) :
                            $_cat = $objectManager->create('Magento\Catalog\Model\Category')->load($_catId);
                            $_filters .= ' ' . $_cat->getData('url_key');
                        endforeach;
                ?>
                <?php
                        $image_type = 'category_page_grid';
                        if($aspect_ratio)
                            $productImage = $_imagehelper->init($_product, $image_type)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                        else
                            $productImage = $_imagehelper->init($_product, $image_type)->resize($image_width, $image_height);
                        $productImageUrl = str_replace("\\",'/', $productImage->getUrl());

                        $_categoryIds = $_product->getCategoryIds();
                        if(count($_categoryIds) > 0 && $_categoryIds[0] != $_berserkhelper->getRootCategoryId() ) {
                            $category = $objectManager->create('Magento\Catalog\Model\Category')->load($_categoryIds[0]);
                            $_category_label = '<span class="brk-sc-flip-four__cat font__family-montserrat brk-bg-primary brk-white-font-color">' . $category->getName() . '</span>';
                        }
                    ?>
                <div class="brk-shop-grid-filter__item <?php echo $_filters . ' ' . $_colClass ?>">
                    <div class="brk-shop-grid-filter-cells lazyload" style="background-image:url('<?php echo $productImageUrl ?>')">
                        <div class="before brk-base-bg-gradient-10deg"></div>
                        <div class="brk-shop-grid-filter-cells__content d-flex flex-wrap align-content-between">
                            <div class="w-100">
                            <?php echo $_category_label; ?>
                            <?php
                                    $product_label = "";
                                    if($_sale_label) {
                                        $orgprice = $_product->getPrice();
                                        $specialprice = $_product->getSpecialPrice();
                                        $specialfromdate = $_product->getSpecialFromDate();
                                        $specialtodate = $_product->getSpecialToDate();
                                        $today = time();
                                        if(!$specialprice)
                                            $specialprice = $orgprice;
                                        if($specialprice < $orgprice) {
                                            if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
                                                $percent = number_format ( ($specialprice - $orgprice) / $orgprice * 100) . '%';
                                                if($_show_percent) $_sale_label = $percent;
                                                $product_label .= '<div class="product-label sale-label brk-sc-card-label">';
                                                $product_label .= '<span class="brk-white-font-color font__family-montserrat font__size-13 font__weight-bold line__height-14 text-uppercase brk-sc-card-label__text">'. $_sale_label .'</span>';
                                                $product_label .= '<span class="brk-sc-card-label__additional-1"></span><span class="brk-sc-card-label__additional-2"></span><span class="brk-sc-card-label__additional-3"></span>';
                                                $product_label .= '</div>';
                                            }
                                        }
                                    }
                                    if($_new_label) {
                                        $now = date("Y-m-d");
                                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                                        if ($newsTo != '' || $newsFrom != ''){
                                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                                $product_label .= '<div class="product-label new-label brk-sc-card-label">';
                                                $product_label .= '<span class="brk-white-font-color font__family-montserrat font__size-13 font__weight-bold line__height-14 text-uppercase brk-sc-card-label__text">'. $_new_label .'</span>';
                                                $product_label .= '<span class="brk-sc-card-label__additional-1"></span><span class="brk-sc-card-label__additional-2"></span><span class="brk-sc-card-label__additional-3"></span>';
                                                $product_label .= '</div>';
                                            }
                                        }
                                    }
                                    if($product_label){
                                        switch ($_label_type) {
                                            case 1:
                                                echo '<div class="product-labels brk-sc-card-labels top-labels">'.$product_label.'</div>';
                                                break;
                                            case 2:
                                                echo '<div class="product-labels brk-sc-card-labels side-labels">'.$product_label.'</div>';
                                                break;
                                            default:
                                                echo '<div class="product-labels brk-sc-card-labels side-labels-cornered">'.$product_label.'</div>';
                                                break;
                                        }
                                        
                                    }
                                ?>
                                <a class="product-item-link"
                                    href="<?php echo $_product->getProductUrl() ?>">
                                        <?php echo $_helper->productAttribute( $_product, $_product->getName(), 'name' ); ?>
                                </a>
                            </div>
                            <div class="w-100 d-flex flex-wrap justify-content-between align-items-end">
                                <div class="brk-shop-grid-filter-cells__rating">
                                    <?php
                                        $_review_model->getEntitySummary($_product);
                                        echo $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW);
                                    ?>
                                </div>
                                <div class="actions-primary ">
                                    <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product);  ?>
                                        <form data-role="tocart-form"  data-product-sku="<?php echo $block->escapeHtml($_product->getSku()); ?>"
                                            action="<?php echo $block->escapeHtml($postParams['action']); ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <?php
                                                echo $block->getProductPrice( $_product );
                                            ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary ">
                                                <i class="fas fa-shopping-cart"></i><span><?php echo $block->escapeHtml(__('Buy')); ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>   
        </div>
    </div>
    
    <script>
        require([
            'jquery',
            'jquery-bridget',
            'isotope',       
            'isotope-skin',
        ], function ($) {
            Berserk.behaviors.sc_grid_filter.attach($('.isotope-grid'));
        });
    </script>

<?php endif;?>