<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form contact contact-pd-left"
      action="<?php echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}' style="padding-top: 50px; padding-bottom: 137px;">
    <fieldset class="fieldset font-black font-family-babas" style="margin-bottom: 0;">
        <legend class="legend"><span class="font-black ft-40-ls-6"><?php echo __('have a question?  Send us a message') ?></span></legend><br />
        <fieldset class="fieldset row">
            <div class="fields col-md-10 col-lg-9" style="padding-top: 35px;">
        <div class="field name required">
            <label class="label" for="name"><span class="ft-25-ls-2"><?php echo __('Full Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php echo __('Full Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field organization ">
            <label class="label" for="organization"><span class="ft-25-ls-2"><?php echo __('organization') ?></span></label>
            <div class="control">
                <input name="name" id="organization" title="<?php echo __('organization') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text"/>
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span class="ft-25-ls-2"><?php echo __('Telephone Number') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php echo __('Telephone Number') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field postal required">
            <label class="label" for="postal"><span class="ft-25-ls-2"><?php echo __('Postal / Zip Code') ?></span></label>
            <div class="control">
                <input name="postal" id="postal" title="<?php echo __('Postal / Zip Code') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span class="ft-25-ls-2"><?php echo __('Email Address') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php echo __('Email Address') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        
        <div class="field comment required">
            <label class="label" for="comment"><span class="ft-25-ls-2"><?php echo __('Questions or Comments') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php echo __('Questions or Comments') ?>" class="input-text" cols="6" rows="8" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="field hear">
            <label class="label" for="hear"><span class="ft-25-ls-2"><?php echo __('How did you hear about us?') ?></span></label>
            <div class="control">
                <input name="hear" id="hear" title="<?php echo __('how did you hear about us?') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
            </div>
        </fieldset>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary" style="padding-bottom: 35px;padding-top: 15px;">
                <span class="ft-25-ls-2" style="margin-left: 40px; margin-right: 40px"><?php echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>
